### ISSUE TITLE
 register_rest_route was called incorrectly

### ISSUE THREAD

**Issue by koraysels** [suomato/luna#2]
in `luna/src/Utils/Router.php `
there is an error that causes this Notice

https://github.com/suomato/luna/blob/fbf0d1307a9fef383c00e9113d534f3b7f9bac4a/src/Utils/Router.php#L12

there is a malformed piece of code there.
The $route['namespace'] cannot end with a / so if we move it to the route parameter the Notice disappeares..

```php
register_rest_route($route['namespace'], '/' . $route['base'], [
```

**Comment by suomato** [comment]
Fixed... finally.
